import { User, Admin } from '../types';

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    role: 'admin',
    phone: '+1 (555) 234-5678',
    address: '123 Main St, San Francisco, CA 94102',
    status: 'Active',
    joinedDate: '2024-01-15',
  },
  {
    id: 2,
    name: 'Sarah Williams',
    email: 'sarah.w@example.com',
    role: 'moderator',
    phone: '+1 (555) 876-5432',
    address: '456 Oak Ave, New York, NY 10001',
    status: 'Active',
    joinedDate: '2024-03-22',
  },
  {
    id: 3,
    name: 'Michael Chen',
    email: 'michael.chen@example.com',
    role: 'user',
    phone: '+1 (555) 345-6789',
    address: '789 Pine Rd, Austin, TX 73301',
    status: 'Active',
    joinedDate: '2024-05-10',
  },
  {
    id: 4,
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    role: 'user',
    phone: '+1 (555) 567-8901',
    address: '321 Elm St, Chicago, IL 60601',
    status: 'Inactive',
    joinedDate: '2024-06-18',
  },
  {
    id: 5,
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    role: 'moderator',
    phone: '+1 (555) 901-2345',
    address: '654 Maple Dr, Seattle, WA 98101',
    status: 'Active',
    joinedDate: '2024-08-05',
  },
];

export const mockAdmins: Admin[] = [
  {
    id: 1,
    name: 'Cody Admin',
    email: 'cody@admin.com',
    role: 'AdminX',
    status: 'Active',
    createdAt: '2023-06-01',
  },
  {
    id: 2,
    name: 'Alex Johnson',
    email: 'alex.johnson@admin.com',
    role: 'Admin',
    status: 'Active',
    createdAt: '2024-01-15',
  },
  {
    id: 3,
    name: 'Sarah Williams',
    email: 'sarah.w@admin.com',
    role: 'Moderator',
    status: 'Active',
    createdAt: '2024-03-22',
  },
];
